version: "3"

services:
  nginx:
    container_name: nginx-container
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - mariadb
      - wordpress
    restart: unless-stopped
    tty: true
    networks:
      - inception-network
    volumes:
      - db-volume:/var/lib/mysql

  mariadb:
    container_name: mariadb-container
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    stdin_open: true
    # expose:
    #   - "3306"
    networks:
      - inception-network
    volumes:
      - db-volume:/var/lib/mysql
    init: true
    env_file: .env

  wordpress:
    container_name: wordpress-container
    depends_on: 
      - mariadb
    env_file: .env
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress-volume:/var/www/html/
    restart: unless-stopped
    tty: true
    # expose:
    #   - "9000"
    networks:
      - inception-network


networks:
  inception-network:
    name: inception-network

volumes:
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/argentumlunae/data/wordpress/data
      o: bind

  db-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/argentumlunae/data/mysql/data
      o: bind
