version: "3.8"

services:
  mariadb:
    env_file: .env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - db-volume:/var/www/html
    restart: unless-stopped
    tty: true
    networks:
      - inception-network

  wordpress:
    depends_on: 
      - mariadb
    env_file: .env
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress-volume:/var/www/html
    restart: unless-stopped
    tty: true
    networks:
      - inception-network

  nginx:
    depends_on:
      - mariadb
      - wordpress
    container_name: nginx
    env_file: .env
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "443:443"
    tty: true
    networks:
      - inception-network

networks:
  inception-network:
    name: inception-network

volumes:
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mteerlin/data/wordpress/

  db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mteerlin/data/mariadb/
