version: "3"

services:
  nginx:
    container_name: nginx
    depends_on:
      - mariadb
      - wordpress
    env_file: .env
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4242:4242"
    tty: true
    networks:
      - inception-network

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - inception-network
    volumes:
      - db-volume:/var/www/html
    init: true
    env_file: .env
    # environment: 
    #   MYSQL_DATABASE: wordpress

  wordpress:
    container_name: wordpress
    depends_on: 
      - mariadb
    env_file: .env
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress-volume:/var/www/html
    restart: unless-stopped
    tty: true
    networks:
      - inception-network


networks:
  inception-network:
    name: inception-network

volumes:
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mteerlin/data/wordpress/

  db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mteerlin/data/mariadb/
