version: "3.8"

services:
  mariadb:
    env_file: ./.env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    expose: 
      - 3306
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped
    tty: true
    networks:
      - network

  wordpress:
    depends_on: 
      - mariadb
    env_file: ./.env
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    expose:
      - 3306
      - 9000
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped
    tty: true
    networks:
      - network

  nginx:
    depends_on:
      - mariadb
      - wordpress
    container_name: nginx
    env_file: ./.env
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    expose: 
      - 9000
    restart: unless-stopped
    ports:
      - "443:443"
    tty: true
    networks:
      - network

  volumes:
    